apiVersion: v1
kind: Pod
metadata:
  name: amazon
spec:
  containers:
    - name: logout
      image: centos
      command: ["/bin/bash", "-c", "sleep 2000"]
      volumeMounts:
        - mountPath: /tmp/hostpath
          name: shree
  volumes:
    - name: shree
      hostPath:
        path: /tmp/mydata
