apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-v1
  labels:
    type: Local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.5.61
    path: "/mnt/shree"
